[package]
name = "toy-raft"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tonic = "0.11"
prost = "0.12"
tokio = { version = "1", features = ["full"] }
thiserror = "1"

[build-dependencies]
tonic-build = "0.11"
anyhow = "1"
